### PR TITLE
fix: Use commit SHA from the event CY-4321

### PR DESCRIPTION
**Pull request by machadoit**
If the event is a pull request, the GITHUB_SHA will have a different commit UUID (the id of a merge commit):
https://help.github.com/en/actions/reference/events-that-trigger-workflows

We need to fetch the correct SHA from the event details that GitHub provides.

Tested with https://github.com/troubleshoot-codacy/eslint-test-prod/pull/5 (that relies on a fork of the action with this changes)

### CODE REVIEW

**Comment by lolgab** [comment]
We solved this in another level in the coverage reporter. It is the coverage reporter itself that defaults to the correct commit uuid without any extra logic in the action side. @franciscodua knows well everything since he did it.
I think we can merge this PR, but also open an investigation task to see if it's worth to extract the provider logic in a library consumed by coverage-reporter and analysis-cli.

**Comment by franciscodua** [comment]
Yes, we already have a special case for the coverage reporter in Github. You can find it [here](https://github.com/codacy/codacy-coverage-reporter/blob/master/src/main/scala/com/codacy/rules/commituuid/providers/GitHubActionProvider.scala#L24)

**Comment by machadoit** [comment]
So that would be a direction that we want the CLI to move? Even if we do it in the future, we should do it here as well:
* We are calling the CLI, and the CLI can receive the commit-uuid as a param, if the action already knows the correct one, can already pass it
* We need to find the correct UUID on this side either way, as there are things that are not done on the CLI, like sending results for the GoSec that does not go through it, and sending the final notification.

That said, we can move on that direction, like you guys mention, but that does not invalidate this PR, correct? It is something that we still need to merge, right? @franciscodua @lolgab

**Comment by lolgab** [comment]
> That said, we can move on that direction, like you guys mention, but that does not invalidate this PR, correct?

Correct!

**Review by lolgab — APPROVED** [review]

**Pull request merged**
